// ═══════════════════════════════════════════════════════
//  DATA — English context → Norwegian answer
//  Each card: { en, no, ctx }
//  en  = English label shown as question
//  no  = Norwegian answer (what player must pick)
//  ctx = small italic context clue
// ═══════════════════════════════════════════════════════

const DB = {

  // ══════════════ RACES ══════════════
  races: {

    // ── ALLIANCE ──
    human: { icon:'👤', faction:'alliance', label:'Human', cards:[
      // Racial traits
      { en:'Perception', no:'Persepsjon', ctx:'Racial — detect stealth' },
      { en:'The Human Spirit', no:'Den menneskelige ånd', ctx:'Racial — Spirit bonus' },
      { en:'Diplomacy', no:'Diplomati', ctx:'Racial — bonus reputation gain' },
      { en:'Sword Specialization', no:'Sverdspesialisering', ctx:'Racial — +5 sword skill' },
      { en:'Mace Specialization', no:'Køllespesialisering', ctx:'Racial — +5 mace skill' },
      // Cities
      { en:'Stormwind City', no:'Stormvindby', ctx:'Human capital city' },
      { en:'Goldshire', no:'Gullskjær', ctx:'Starting village' },
      { en:'Westfall', no:'Vestfall', ctx:'Human farming zone' },
      { en:'Elwynn Forest', no:'Elwynn-skogen', ctx:'Starting zone for Humans' },
      { en:'Redridge Mountains', no:'Rødtind-fjellene', ctx:'Human mid-level zone' },
      { en:'Duskwood', no:'Skumringsskog', ctx:'Dark human zone, undead threat' },
      { en:'Stranglethorn Vale', no:'Kvelningsdalen', ctx:'Contested jungle zone' },
      // Lore
      { en:'King Varian Wrynn', no:'Kongen Varian Wrynn', ctx:'King of Stormwind' },
      { en:'Stormwind Keep', no:'Stormvindborgen', ctx:'Palace in Stormwind' },
      { en:'The Cathedral of Light', no:'Lysets katedral', ctx:'Paladin/Priest hub' },
    ]},

    dwarf: { icon:'🪨', faction:'alliance', label:'Dwarf', cards:[
      { en:'Stoneform', no:'Steinform', ctx:'Racial — remove poison/bleed/disease' },
      { en:'Find Treasure', no:'Finn skatt', ctx:'Racial — minimap treasure tracking' },
      { en:'Gun Specialization', no:'Skytevåpenspesialisering', ctx:'Racial — +5 gun skill' },
      { en:'Frost Resistance', no:'Frostmotstand', ctx:'Racial — passive resist' },
      { en:'Ironforge', no:'Jernsmie', ctx:'Dwarf capital city' },
      { en:'Dun Morogh', no:'Dun Morogh', ctx:'Dwarf starting zone' },
      { en:'Loch Modan', no:'Loch Modan', ctx:'Dwarf secondary zone' },
      { en:'Wetlands', no:'Myrlandene', ctx:'Zone connecting to Arathi' },
      { en:'The Bronzebeard Clan', no:'Bronzeskjegg-klanen', ctx:'Ruling dwarf clan' },
      { en:'The Great Forge', no:'Den store smien', ctx:'Center of Ironforge' },
      { en:'King Magni Bronzebeard', no:'Kongen Magni Bronzeskjegg', ctx:'King of Ironforge' },
    ]},

    nightelf: { icon:'🌙', faction:'alliance', label:'Night Elf', cards:[
      { en:'Shadowmeld', no:'Skyggefletting', ctx:'Racial — vanish in place' },
      { en:'Quickness', no:'Kvikkhets gave', ctx:'Racial — dodge chance' },
      { en:'Wisp Spirit', no:'Lygtemandsånd', ctx:'Racial — faster ghost form' },
      { en:'Nature Resistance', no:'Naturmotstand', ctx:'Racial — passive resist' },
      { en:'Darnassus', no:'Darnassus', ctx:'Night Elf capital city' },
      { en:'Teldrassil', no:'Teldrassil', ctx:'Starting island of Night Elves' },
      { en:'Darkshore', no:'Mørkekyst', ctx:'Night Elf second zone' },
      { en:'Ashenvale', no:'Askedalen', ctx:'Contested forested zone' },
      { en:'Felwood', no:'Ondslygsskogen', ctx:'Corrupted forest' },
      { en:'Moonglade', no:'Månelyseng', ctx:'Druid sanctuary' },
      { en:'The World Tree', no:'Verdenstre', ctx:'Ancient night elf symbol' },
      { en:'Tyrande Whisperwind', no:'Tyrande Hviskvind', ctx:'High Priestess of Elune' },
    ]},

    gnome: { icon:'⚙', faction:'alliance', label:'Gnome', cards:[
      { en:'Escape Artist', no:'Rømningskunstner', ctx:'Racial — escape snare/root' },
      { en:'Engineering Specialization', no:'Ingeniørspesialisering', ctx:'Racial — +15 Engineering' },
      { en:'Expansive Mind', no:'Ekspansiv sinn', ctx:'Racial — Intellect bonus' },
      { en:'Arcane Resistance', no:'Arkansk motstand', ctx:'Racial — passive resist' },
      { en:'Gnomeregan', no:'Gnomeregan', ctx:'Lost gnome city (instance)' },
      { en:'Tinker Town', no:'Tinkerstad', ctx:'Gnome district in Ironforge' },
      { en:'Dun Morogh', no:'Dun Morogh', ctx:'Gnome starting area (shared)' },
    ]},

    draenei: { icon:'💠', faction:'alliance', label:'Draenei (TBC)', cards:[
      { en:'Gift of the Naaru', no:'Naaruenes gave', ctx:'Racial — HoT heal' },
      { en:'Heroic Presence', no:'Heroisk tilstedeværelse', ctx:'Racial — +1% Hit aura' },
      { en:'Shadow Resistance', no:'Skyggmotstand', ctx:'Racial — passive resist' },
      { en:'Gemcutting', no:'Edelsteinsliper', ctx:'Racial — +5 Jewelcrafting' },
      { en:'The Exodar', no:'Eksodaren', ctx:'Draenei capital ship/city (TBC)' },
      { en:'Azuremyst Isle', no:'Azuremyst-øya', ctx:'Draenei starting zone (TBC)' },
      { en:'Bloodmyst Isle', no:'Blodmyst-øya', ctx:'Draenei second zone (TBC)' },
      { en:'Velen the Prophet', no:'Velen profeten', ctx:'Draenei leader' },
    ]},

    // ── HORDE ──
    orc: { icon:'💀', faction:'horde', label:'Orc', cards:[
      { en:'Blood Fury', no:'Blodfurie', ctx:'Racial — Attack Power burst' },
      { en:'Hardiness', no:'Hardhet', ctx:'Racial — stun resist chance' },
      { en:'Axe Specialization', no:'Øksespesialisering', ctx:'Racial — +5 axe skill' },
      { en:'Command', no:'Kommando', ctx:'Racial — pet damage bonus' },
      { en:'Orgrimmar', no:'Orgrimmar', ctx:'Orc capital city' },
      { en:'Durotar', no:'Durotar', ctx:'Orc starting zone' },
      { en:'The Barrens', no:'Det øde landet', ctx:'Vast Horde zone' },
      { en:'Warsong Gulch', no:'Krigsangdalen', ctx:'Orc BG, classic battleground' },
      { en:'Thrall', no:'Thrall', ctx:'Warchief of the Horde' },
      { en:'Valley of Trials', no:'Prøvedalen', ctx:'Orc starting subzone' },
    ]},

    troll: { icon:'🦷', faction:'horde', label:'Troll', cards:[
      { en:'Berserking', no:'Berserkergang', ctx:'Racial — attack/cast speed burst' },
      { en:'Beast Slaying', no:'Dyreslakt', ctx:'Racial — bonus damage vs beasts' },
      { en:'Regeneration', no:'Regenerasjon', ctx:'Racial — HP regen bonus' },
      { en:'Throwing Specialization', no:'Kastevåpenspesialisering', ctx:'Racial — +5 throwing' },
      { en:'Sen\'jin Village', no:'Sen\'jin landsby', ctx:'Troll starting village' },
      { en:'Echo Isles', no:'Ekkoholmene', ctx:'Troll homeland' },
      { en:'Stranglethorn Vale', no:'Kvelningsdalen', ctx:'Contested zone, troll ruins' },
      { en:'Zul\'Gurub', no:'Zul\'Gurub', ctx:'Troll raid instance in STV' },
      { en:'Vol\'jin', no:'Vol\'jin', ctx:'Darkspear Troll chieftain' },
    ]},

    tauren: { icon:'🐃', faction:'horde', label:'Tauren', cards:[
      { en:'War Stomp', no:'Krigstamp', ctx:'Racial — AoE stun' },
      { en:'Endurance', no:'Utholdenhet', ctx:'Racial — base Health bonus' },
      { en:'Nature Resistance', no:'Naturmotstand', ctx:'Racial — passive resist' },
      { en:'Cultivation', no:'Dyrking', ctx:'Racial — +15 Herbalism' },
      { en:'Thunder Bluff', no:'Tordenvollen', ctx:'Tauren capital city' },
      { en:'Mulgore', no:'Mulgore', ctx:'Tauren starting zone' },
      { en:'Thousand Needles', no:'Tusen nåler', ctx:'Tauren secondary zone' },
      { en:'Feralas', no:'Feralas', ctx:'Contested zone, tauren presence' },
      { en:'High Chieftain Cairne', no:'Høvding Cairne', ctx:'Tauren leader' },
      { en:'Red Cloud Mesa', no:'Rødsky-platået', ctx:'Tauren starting subzone' },
    ]},

    undead: { icon:'💀', faction:'horde', label:'Undead', cards:[
      { en:'Will of the Forsaken', no:'De fortaptes vilje', ctx:'Racial — break fear/charm/sleep' },
      { en:'Cannibalize', no:'Kannibalisere', ctx:'Racial — eat corpses for HP regen' },
      { en:'Underwater Breathing', no:'Undervannspust', ctx:'Racial — extended breath' },
      { en:'Shadow Resistance', no:'Skyggmotstand', ctx:'Racial — passive resist' },
      { en:'Undercity', no:'Underbyen', ctx:'Forsaken capital city' },
      { en:'Tirisfal Glades', no:'Tirisfal-engene', ctx:'Undead starting zone' },
      { en:'Silverpine Forest', no:'Sølvfuruskogen', ctx:'Undead secondary zone' },
      { en:'Hillsbrad Foothills', no:'Åsmark-forlandet', ctx:'Contested zone near Undercity' },
      { en:'Sylvanas Windrunner', no:'Sylvanas Vindløper', ctx:'Banshee Queen of the Forsaken' },
      { en:'The Apothecary', no:'Apotekeren', ctx:'Forsaken alchemist faction' },
    ]},

    bloodelf: { icon:'🔮', faction:'horde', label:'Blood Elf (TBC)', cards:[
      { en:'Arcane Torrent', no:'Arkanetorrent', ctx:'Racial — silence + restore resource' },
      { en:'Mana Tap', no:'Manatapping', ctx:'Racial — drain enemy mana stacks' },
      { en:'Arcane Affinity', no:'Arkanetilhørighet', ctx:'Racial — +10 Enchanting' },
      { en:'Magic Resistance', no:'Magiresistens', ctx:'Racial — spell hit reduction' },
      { en:'Silvermoon City', no:'Sølvmåneby', ctx:'Blood Elf capital (TBC)' },
      { en:'Eversong Woods', no:'Evigangskogen', ctx:'Blood Elf starting zone (TBC)' },
      { en:'Ghostlands', no:'Spøkelseslandet', ctx:'Blood Elf second zone (TBC)' },
      { en:'Prince Kael\'thas', no:'Prins Kael\'thas', ctx:'Blood Elf prince (TBC villain)' },
      { en:'Lady Liadrin', no:'Lady Liadrin', ctx:'Blood Knight Matriarch' },
    ]},
  },

  // ══════════════ CLASSES ══════════════
  classes: {

    paladin: { icon:'⚖', faction:'alliance', label:'Paladin', cards:{
      weapons:[
        { en:'One-handed sword', no:'Etterhåndssverd', ctx:'Paladin weapon' },
        { en:'Two-handed sword', no:'Tohåndssverd', ctx:'Ret Paladin weapon' },
        { en:'One-handed mace', no:'Etterhåndskølle', ctx:'Common paladin weapon' },
        { en:'Two-handed mace', no:'Tohåndskølle', ctx:'Holy/Ret weapon' },
        { en:'Shield', no:'Skjold', ctx:'Holy/Prot offhand' },
        { en:'Polearm', no:'Stangskyts', ctx:'Paladin can use' },
      ],
      armor:[
        { en:'Plate armor', no:'Platepanser', ctx:'Paladin end armor (lvl 40+)' },
        { en:'Mail armor', no:'Ringbrynje', ctx:'Paladin armor before plate' },
        { en:'Leather armor', no:'Lærpanser', ctx:'Early paladin armor' },
        { en:'Cloth armor', no:'Tøypanser', ctx:'Very early paladin armor' },
      ],
      abilities:[
        { en:'Holy Light', no:'Hellig lys', ctx:'Main heal spell' },
        { en:'Flash of Light', no:'Lysglimt', ctx:'Fast small heal' },
        { en:'Lay on Hands', no:'Håndspåleggelse', ctx:'Emergency full heal, long CD' },
        { en:'Divine Shield', no:'Guddommelig skjold', ctx:'Bubble — invulnerable 12s' },
        { en:'Blessing of Kings', no:'Kongenes velsignelse', ctx:'Stat % buff' },
        { en:'Blessing of Might', no:'Kraftens velsignelse', ctx:'AP/SP buff' },
        { en:'Blessing of Wisdom', no:'Visdomens velsignelse', ctx:'Mana regen buff' },
        { en:'Consecration', no:'Innvielse', ctx:'AoE ground damage' },
        { en:'Hammer of Justice', no:'Rettferdighetens hammer', ctx:'Stun interrupt' },
        { en:'Seal of Righteousness', no:'Rettferdighets segl', ctx:'Holy proc on hits' },
        { en:'Judgement', no:'Dom', ctx:'Consume seal for effect' },
        { en:'Aura of Retribution', no:'Gjengjeldelsesaura', ctx:'Damage aura' },
        { en:'Devotion Aura', no:'Hengivenhetsaura', ctx:'Armor aura' },
        { en:'Righteous Fury', no:'Hellig raseri', ctx:'Threat generation' },
        { en:'Holy Wrath', no:'Hellig vrede', ctx:'AoE undead stun/dmg' },
      ],
      playstyle:[
        { en:'Healer', no:'Healer', ctx:'Holy spec role' },
        { en:'Tank', no:'Tank', ctx:'Protection spec role' },
        { en:'Retribution DPS', no:'Gjengjeldelses-DPS', ctx:'Ret spec role' },
        { en:'Support / Buffer', no:'Støttespiller', ctx:'Paladin utility role' },
        { en:'Mana management', no:'Manaforvaltning', ctx:'Key paladin skill' },
        { en:'Aura switching', no:'Aurabytte', ctx:'Situational playstyle' },
        { en:'Blessing rotation', no:'Velsignelsesrotasjon', ctx:'Group buffing' },
      ],
      advanced:[
        { en:'Divine Favor', no:'Guddommelig gunst', ctx:'Next heal is crit' },
        { en:'Holy Shock', no:'Hellig sjokk', ctx:'Instant heal or damage' },
        { en:'Sanctity Aura', no:'Hellighetsaura', ctx:'Holy damage aura' },
        { en:'Repentance', no:'Anger', ctx:'Ret CC, Humanoid only' },
        { en:'Spiritual Attunement', no:'Åndelig innstilling', ctx:'Mana from heals taken' },
        { en:'Seal of Light', no:'Lyssegl', ctx:'Heal on hit' },
        { en:'Seal of Wisdom', no:'Visdomssegl', ctx:'Mana restore on hit' },
      ],
    }},

    warrior: { icon:'⚔', faction:'both', label:'Warrior', cards:{
      weapons:[
        { en:'Two-handed axe', no:'Tohåndsøks', ctx:'Fury warrior weapon' },
        { en:'One-handed sword', no:'Etterhåndssverd', ctx:'Arms or tank weapon' },
        { en:'Two-handed sword', no:'Tohåndssverd', ctx:'Arms warrior weapon' },
        { en:'One-handed axe', no:'Etterhåndsøks', ctx:'Dual wield fury' },
        { en:'Shield', no:'Skjold', ctx:'Protection tank offhand' },
        { en:'Polearm', no:'Stangskyts', ctx:'Arms weapon option' },
        { en:'Fist weapon', no:'Nevevåpen', ctx:'Fury dual wield option' },
      ],
      armor:[
        { en:'Plate armor', no:'Platepanser', ctx:'Warrior primary armor' },
        { en:'Mail armor', no:'Ringbrynje', ctx:'Warrior armor before plate' },
        { en:'Leather armor', no:'Lærpanser', ctx:'Very early warrior armor' },
      ],
      abilities:[
        { en:'Charge', no:'Ladning', ctx:'Open combat, generate rage' },
        { en:'Heroic Strike', no:'Heroisk slag', ctx:'Rage dump melee attack' },
        { en:'Shield Bash', no:'Skjoldsmell', ctx:'Interrupt + shield attack' },
        { en:'Mortal Strike', no:'Dødelig slag', ctx:'Arms signature ability' },
        { en:'Whirlwind', no:'Hvirvelvind', ctx:'Fury AoE spin attack' },
        { en:'Bloodthirst', no:'Blodtørst', ctx:'Fury signature ability' },
        { en:'Shield Wall', no:'Skjoldmur', ctx:'Defensive cooldown — 75% dmg red' },
        { en:'Last Stand', no:'Siste forsvar', ctx:'Emergency HP boost' },
        { en:'Revenge', no:'Hevn', ctx:'Tank counter-attack' },
        { en:'Sunder Armor', no:'Splitt rustning', ctx:'Tank debuff, reduce armor' },
        { en:'Demoralizing Shout', no:'Demoraliserende rop', ctx:'Reduce enemy AP' },
        { en:'Battle Shout', no:'Kamprop', ctx:'AP buff for party' },
        { en:'Overpower', no:'Overvelde', ctx:'Arms talent proc attack' },
        { en:'Execute', no:'Henrette', ctx:'Sub-20% finisher' },
        { en:'Intercept', no:'Avskjære', ctx:'Charge in combat, stun' },
      ],
      playstyle:[
        { en:'Main Tank', no:'Hovedtank', ctx:'Protection warrior raid role' },
        { en:'Off Tank', no:'Reservetank', ctx:'Secondary tank role' },
        { en:'DPS', no:'Skadeyting', ctx:'Arms or Fury spec' },
        { en:'Rage resource', no:'Raseriressurs', ctx:'Warrior resource system' },
        { en:'Stance management', no:'Stillingsstyring', ctx:'Battle/Defensive/Berserker' },
        { en:'Dual wield', no:'Tohåndsbruk', ctx:'Fury playstyle' },
        { en:'Threat management', no:'Trusselhåndtering', ctx:'Tank core skill' },
      ],
      advanced:[
        { en:'Deep Wounds', no:'Dype sår', ctx:'Arms talent — bleed on crit' },
        { en:'Flurry', no:'Byge', ctx:'Fury talent — attack speed after crit' },
        { en:'Impale', no:'Spidde', ctx:'Arms talent — crit bonus' },
        { en:'Shield Slam', no:'Skjoldsmell', ctx:'Prot tank signature hit' },
        { en:'Berserker Rage', no:'Berserkerraseri', ctx:'Break fear, gain rage' },
      ],
    }},

    hunter: { icon:'🏹', faction:'both', label:'Hunter', cards:{
      weapons:[
        { en:'Bow', no:'Bue', ctx:'Hunter ranged weapon' },
        { en:'Gun', no:'Skytevåpen', ctx:'Hunter ranged weapon' },
        { en:'Crossbow', no:'Armbrøst', ctx:'Hunter ranged weapon' },
        { en:'One-handed axe', no:'Etterhåndsøks', ctx:'Hunter melee' },
        { en:'One-handed sword', no:'Etterhåndssverd', ctx:'Hunter melee' },
        { en:'Polearm', no:'Stangskyts', ctx:'Hunter melee' },
        { en:'Staff', no:'Stav', ctx:'Hunter melee option' },
        { en:'Two-handed axe', no:'Tohåndsøks', ctx:'Hunter melee' },
      ],
      armor:[
        { en:'Mail armor', no:'Ringbrynje', ctx:'Hunter main armor (lvl 40+)' },
        { en:'Leather armor', no:'Lærpanser', ctx:'Hunter early armor' },
      ],
      abilities:[
        { en:'Auto Shot', no:'Autoskudd', ctx:'Constant ranged attack' },
        { en:'Aimed Shot', no:'Siktet skudd', ctx:'Slow, high damage shot' },
        { en:'Multi-Shot', no:'Flerskudd', ctx:'AoE ranged attack' },
        { en:'Arcane Shot', no:'Arkaneskudd', ctx:'Instant shot, no pushback' },
        { en:'Hunter\'s Mark', no:'Jegermerket', ctx:'Ranged AP debuff on target' },
        { en:'Serpent Sting', no:'Slangesting', ctx:'DoT poison' },
        { en:'Aspect of the Hawk', no:'Haukaspectet', ctx:'AP bonus aura' },
        { en:'Aspect of the Cheetah', no:'Gepardaspektet', ctx:'Movement speed aura' },
        { en:'Feign Death', no:'Spille død', ctx:'Drop threat / escape' },
        { en:'Freezing Trap', no:'Frysingsfelle', ctx:'CC trap' },
        { en:'Immolation Trap', no:'Brenningsfelle', ctx:'Fire damage trap' },
        { en:'Wing Clip', no:'Vingekutting', ctx:'Slow melee snare' },
        { en:'Rapid Fire', no:'Rask ild', ctx:'Attack speed burst cooldown' },
        { en:'Bestial Wrath', no:'Bestialsk raseri', ctx:'BM pet damage burst' },
        { en:'Send Pet', no:'Send kjæledyr', ctx:'Control pet command' },
      ],
      playstyle:[
        { en:'Beast Mastery', no:'Dyremestring', ctx:'BM spec — pet focused' },
        { en:'Marksmanship', no:'Skytterkunst', ctx:'MM spec — ranged burst' },
        { en:'Survival', no:'Overlevelse', ctx:'SV spec — traps/utility' },
        { en:'Mana management', no:'Manaforvaltning', ctx:'Hunter resource' },
        { en:'Pet control', no:'Kjæledyrkontroll', ctx:'Core BM skill' },
        { en:'Kiting', no:'Drage-styring', ctx:'Pull enemies away while shooting' },
        { en:'Dead Zone', no:'Dødssone', ctx:'Mid-range gap melee/ranged' },
      ],
      advanced:[
        { en:'Trueshot Aura', no:'Presisjonsskuddsaura', ctx:'MM raid buff — AP' },
        { en:'Scatter Shot', no:'Spredningsskudd', ctx:'Disorient CC shot' },
        { en:'Silencing Shot', no:'Taushetsskudd', ctx:'MM interrupt' },
        { en:'Wyvern Sting', no:'Vuivernsting', ctx:'SV sleep DoT' },
        { en:'Readiness', no:'Beredskap', ctx:'Reset all cooldowns' },
      ],
    }},

    druid: { icon:'🌿', faction:'alliance', label:'Druid', cards:{
      weapons:[
        { en:'Staff', no:'Stav', ctx:'Druid main weapon' },
        { en:'Mace', no:'Kølle', ctx:'Druid weapon' },
        { en:'Fist weapon', no:'Nevevåpen', ctx:'Druid weapon (Feral)' },
        { en:'Dagger', no:'Dolk', ctx:'Druid weapon (caster)' },
        { en:'Idol', no:'Idol', ctx:'Druid relic slot item' },
      ],
      armor:[
        { en:'Leather armor', no:'Lærpanser', ctx:'Druid only armor' },
        { en:'Cloth armor', no:'Tøypanser', ctx:'Druid early armor' },
      ],
      abilities:[
        { en:'Rejuvenation', no:'Foryngelse', ctx:'HoT — main Resto heal' },
        { en:'Regrowth', no:'Gjenvekst', ctx:'HoT + direct heal' },
        { en:'Healing Touch', no:'Helbredende berøring', ctx:'Slow big heal' },
        { en:'Tranquility', no:'Ro', ctx:'AoE raid channelled heal' },
        { en:'Moonfire', no:'Månebål', ctx:'Balance dot/nuke' },
        { en:'Starfire', no:'Stjernebål', ctx:'Balance filler nuke' },
        { en:'Wrath', no:'Vrede', ctx:'Balance fast nuke' },
        { en:'Insect Swarm', no:'Insektsverm', ctx:'Balance DoT debuff' },
        { en:'Faerie Fire', no:'Fealys ild', ctx:'Armor debuff, no stealth' },
        { en:'Shapeshift', no:'Formskifte', ctx:'Core druid mechanic' },
        { en:'Bear Form', no:'Bjørnform', ctx:'Tank form' },
        { en:'Cat Form', no:'Katteform', ctx:'Stealth/DPS form' },
        { en:'Travel Form', no:'Reiseform', ctx:'Cheetah movement form' },
        { en:'Aquatic Form', no:'Vannform', ctx:'Swim speed form' },
        { en:'Moonkin Form', no:'Månehøneform', ctx:'Balance caster form' },
        { en:'Innervate', no:'Innervasjon', ctx:'Mana regen cooldown for healer' },
        { en:'Rebirth', no:'Gjenfødsel', ctx:'Combat rez (battle rez)' },
      ],
      playstyle:[
        { en:'Restoration', no:'Gjenoppretting', ctx:'Healing spec' },
        { en:'Feral Combat', no:'Vill kamp', ctx:'Tank/Melee DPS spec' },
        { en:'Balance', no:'Balanse', ctx:'Caster DPS spec' },
        { en:'Hybrid utility', no:'Hybridnytte', ctx:'Druid strength — many roles' },
        { en:'Energy resource (cat)', no:'Energiressurs (katt)', ctx:'Cat form uses Energy' },
        { en:'Rage resource (bear)', no:'Raseriressurs (bjørn)', ctx:'Bear form uses Rage' },
        { en:'Combo points', no:'Kombopoeng', ctx:'Cat form finisher system' },
      ],
      advanced:[
        { en:'Nature\'s Swiftness', no:'Naturens hurtighet', ctx:'Instant cast cooldown' },
        { en:'Swiftmend', no:'Hurtigléking', ctx:'Consume HoT for instant heal' },
        { en:'Barkskin', no:'Barkskinn', ctx:'Damage reduction cooldown' },
        { en:'Feral Charge', no:'Vill ladning', ctx:'Bear charge interrupt' },
        { en:'Pounce', no:'Kast seg over', ctx:'Cat stealth stun opener' },
      ],
    }},

    priest: { icon:'✝', faction:'both', label:'Priest', cards:{
      weapons:[
        { en:'Staff', no:'Stav', ctx:'Priest main weapon' },
        { en:'Wand', no:'Tryllestav', ctx:'Priest ranged — efficient damage' },
        { en:'Dagger', no:'Dolk', ctx:'Priest offhand combo' },
        { en:'Mace', no:'Kølle', ctx:'Priest weapon' },
      ],
      armor:[
        { en:'Cloth armor', no:'Tøypanser', ctx:'Priest only armor' },
      ],
      abilities:[
        { en:'Power Word: Shield', no:'Kraftord: Skjold', ctx:'Absorb bubble — no pushback' },
        { en:'Renew', no:'Forny', ctx:'HoT heal' },
        { en:'Flash Heal', no:'Blitsheling', ctx:'Fast small heal' },
        { en:'Greater Heal', no:'Stor heling', ctx:'Slow big heal' },
        { en:'Prayer of Healing', no:'Helbredelsens bønn', ctx:'AoE group heal' },
        { en:'Prayer of Mending', no:'Reparasjonens bønn', ctx:'Bouncing heal (TBC)' },
        { en:'Dispel Magic', no:'Spredde magi', ctx:'Remove buffs/debuffs' },
        { en:'Mind Blast', no:'Tankeknall', ctx:'Shadow nuke — instant threat' },
        { en:'Shadow Word: Pain', no:'Skyggord: Smerte', ctx:'Shadow DoT' },
        { en:'Vampiric Embrace', no:'Vampyrisk omfavnelse', ctx:'Shadow lifesteal aura' },
        { en:'Shadowform', no:'Skyggform', ctx:'Shadow spec form — +15% shadow dmg' },
        { en:'Mind Flay', no:'Tankesetting', ctx:'Shadow channelled DoT/snare' },
        { en:'Fade', no:'Bleikne', ctx:'Drop threat temporarily' },
        { en:'Inner Fire', no:'Indre ild', ctx:'Armor + spell power self-buff' },
        { en:'Resurrection', no:'Oppstandelse', ctx:'Out of combat rez' },
        { en:'Fear Ward', no:'Fryktvern', ctx:'Dwarf Priest racial (Classic)' },
      ],
      playstyle:[
        { en:'Holy healing', no:'Hellig heling', ctx:'Main raid healer spec' },
        { en:'Discipline', no:'Disiplin', ctx:'Shield/hybrid spec' },
        { en:'Shadow DPS', no:'Skygge-DPS', ctx:'Caster DPS spec' },
        { en:'Mana battery', no:'Manabatteri', ctx:'Shadow priest TBC raid role' },
        { en:'Dispel duty', no:'Bortspredningsoppgave', ctx:'Key priest utility' },
      ],
      advanced:[
        { en:'Vampiric Touch', no:'Vampyrisk berøring', ctx:'TBC shadow DoT — mana regen' },
        { en:'Circle of Healing', no:'Helingssirkel', ctx:'TBC Holy AoE smart heal' },
        { en:'Pain Suppression', no:'Smertedemping', ctx:'TBC Disc — 40% dmg red' },
        { en:'Surge of Light', no:'Lysbølge', ctx:'Holy free instant heal proc' },
      ],
    }},

    shaman: { icon:'⚡', faction:'horde', label:'Shaman', cards:{
      weapons:[
        { en:'One-handed mace', no:'Etterhåndskølle', ctx:'Shaman weapon' },
        { en:'Two-handed mace', no:'Tohåndskølle', ctx:'Enhancement weapon' },
        { en:'Staff', no:'Stav', ctx:'Shaman caster weapon' },
        { en:'Fist weapon', no:'Nevevåpen', ctx:'Enhancement weapon' },
        { en:'Dagger', no:'Dolk', ctx:'Shaman offhand' },
        { en:'Shield', no:'Skjold', ctx:'Shaman offhand' },
        { en:'Totem', no:'Totem', ctx:'Shaman ground utility item' },
      ],
      armor:[
        { en:'Mail armor', no:'Ringbrynje', ctx:'Shaman main armor (lvl 40+)' },
        { en:'Leather armor', no:'Lærpanser', ctx:'Shaman early armor' },
      ],
      abilities:[
        { en:'Chain Heal', no:'Kjedeheling', ctx:'Bouncing AoE heal — best in slot' },
        { en:'Healing Wave', no:'Helbredende bølge', ctx:'Main single-target heal' },
        { en:'Lesser Healing Wave', no:'Liten helbredende bølge', ctx:'Fast small heal' },
        { en:'Chain Lightning', no:'Kjedeblynedslag', ctx:'AoE lightning' },
        { en:'Lightning Bolt', no:'Lynnedslag', ctx:'Basic shaman nuke' },
        { en:'Earth Shock', no:'Jordsjokk', ctx:'Interrupt + nature dmg' },
        { en:'Frost Shock', no:'Frostsjokk', ctx:'Snare + frost damage' },
        { en:'Flame Shock', no:'Flammsjokk', ctx:'Fire DoT' },
        { en:'Windfury Totem', no:'Vindraseritotem', ctx:'Melee attack speed buff totem' },
        { en:'Mana Spring Totem', no:'Manakilde-totem', ctx:'Mana regen totem' },
        { en:'Strength of Earth Totem', no:'Jordens styrke-totem', ctx:'Strength/Agi totem' },
        { en:'Flametongue Totem', no:'Ildtunge-totem', ctx:'Spell damage totem' },
        { en:'Grounding Totem', no:'Jordingstotem', ctx:'Absorb one spell' },
        { en:'Tremor Totem', no:'Skjelvingstotem', ctx:'Break fear/charm' },
        { en:'Ghost Wolf', no:'Åndsvarg', ctx:'Movement speed travel form' },
      ],
      playstyle:[
        { en:'Restoration', no:'Gjenoppretting', ctx:'Healing spec' },
        { en:'Enhancement', no:'Forbedring', ctx:'Melee DPS spec' },
        { en:'Elemental', no:'Elementær', ctx:'Caster DPS spec' },
        { en:'Totem synergy', no:'Totemsynergi', ctx:'Place all 4 totem types' },
        { en:'Mana efficiency', no:'Manaeffektivitet', ctx:'Resto key skill' },
      ],
      advanced:[
        { en:'Nature\'s Swiftness', no:'Naturens hurtighet', ctx:'Instant cast cooldown' },
        { en:'Elemental Mastery', no:'Elementærmestring', ctx:'Ele — free instant cast' },
        { en:'Stormstrike', no:'Stormslag', ctx:'Enhancement signature attack' },
        { en:'Shamanistic Rage', no:'Sjamansk raseri', ctx:'Enhancement mana return' },
      ],
    }},

    mage: { icon:'🔮', faction:'alliance', label:'Mage', cards:{
      weapons:[
        { en:'Staff', no:'Stav', ctx:'Mage main weapon' },
        { en:'Wand', no:'Tryllestav', ctx:'Mage ranged DPS between casts' },
        { en:'Dagger', no:'Dolk', ctx:'Mage offhand weapon' },
        { en:'Sword (one-handed)', no:'Etterhåndssverd', ctx:'Mage weapon option' },
      ],
      armor:[
        { en:'Cloth armor', no:'Tøypanser', ctx:'Mage only armor' },
      ],
      abilities:[
        { en:'Fireball', no:'Ildball', ctx:'Fire main nuke' },
        { en:'Frostbolt', no:'Frostpil', ctx:'Frost main nuke + snare' },
        { en:'Arcane Blast', no:'Arkansprengning', ctx:'TBC Arcane signature' },
        { en:'Blizzard', no:'Snøstorm', ctx:'Frost AoE channelled' },
        { en:'Flamestrike', no:'Flammeslag', ctx:'Fire AoE ground spell' },
        { en:'Frost Nova', no:'Frostnova', ctx:'AoE root near mage' },
        { en:'Ice Block', no:'Isblokk', ctx:'Immune bubble — full CC' },
        { en:'Blink', no:'Blink', ctx:'Teleport 20 yards forward' },
        { en:'Polymorph', no:'Polymorfi', ctx:'Sheep — CC transform' },
        { en:'Arcane Intellect', no:'Arkaneintelligens', ctx:'Group INT buff' },
        { en:'Mage Armor', no:'Tryllekunstnerarmor', ctx:'Mana regen armor buff' },
        { en:'Ice Armor', no:'Isarmor', ctx:'Chill attackers armor buff' },
        { en:'Counterspell', no:'Mottrylling', ctx:'Interrupt + school lock' },
        { en:'Evocation', no:'Besverging', ctx:'Mana restore channelled' },
        { en:'Presence of Mind', no:'Sinnets nærvær', ctx:'Arcane — next cast instant' },
      ],
      playstyle:[
        { en:'Fire DPS', no:'Ild-DPS', ctx:'Fire spec — strong PvE' },
        { en:'Frost DPS', no:'Frost-DPS', ctx:'Frost spec — strong PvP/kiting' },
        { en:'Arcane DPS', no:'Arkan-DPS', ctx:'TBC arcane — mana burn' },
        { en:'Crowd control', no:'Mengdekontroll', ctx:'Sheep/Nova key utility' },
        { en:'Decursing', no:'Fjerne forbannelse', ctx:'Remove curses in raid' },
        { en:'Kiting', no:'Drage-styring', ctx:'Root/slow and run' },
      ],
      advanced:[
        { en:'Combustion', no:'Forbrenning', ctx:'Fire crit stacking cooldown' },
        { en:'Ice Lance', no:'Isspyd', ctx:'Frost instant — triple vs frozen' },
        { en:'Deep Freeze', no:'Dyp frysing', ctx:'Frost stun on frozen target' },
        { en:'Spell Power', no:'Trolldomskraft', ctx:'Mage main stat' },
        { en:'Hit Rating', no:'Treffsikkerhetsrating', ctx:'Spell hit to cap' },
      ],
    }},

    warlock: { icon:'🔥', faction:'both', label:'Warlock', cards:{
      weapons:[
        { en:'Staff', no:'Stav', ctx:'Warlock main weapon' },
        { en:'Wand', no:'Tryllestav', ctx:'Warlock ranged filler' },
        { en:'Dagger', no:'Dolk', ctx:'Warlock weapon' },
        { en:'Sword (one-handed)', no:'Etterhåndssverd', ctx:'Warlock weapon' },
      ],
      armor:[
        { en:'Cloth armor', no:'Tøypanser', ctx:'Warlock only armor' },
      ],
      abilities:[
        { en:'Shadow Bolt', no:'Skyggebolt', ctx:'Main shadow nuke' },
        { en:'Corruption', no:'Fordervelse', ctx:'Main DoT shadow' },
        { en:'Curse of Agony', no:'Lidelsens forbannelse', ctx:'Main damage curse' },
        { en:'Curse of the Elements', no:'Elementenes forbannelse', ctx:'Magic resist debuff' },
        { en:'Curse of Weakness', no:'Svakhetens forbannelse', ctx:'AP reduction debuff' },
        { en:'Immolate', no:'Brenning', ctx:'Fire DoT opener' },
        { en:'Searing Pain', no:'Sviende smerte', ctx:'High threat fire nuke' },
        { en:'Rain of Fire', no:'Ildregn', ctx:'AoE fire channelled' },
        { en:'Fear', no:'Frykt', ctx:'Humanoid/beast flee CC' },
        { en:'Banish', no:'Forvisning', ctx:'Demon/elemental CC' },
        { en:'Soul Stone', no:'Sjelstein', ctx:'Res item on one ally' },
        { en:'Healthstone', no:'Helsesten', ctx:'HP potion conjure' },
        { en:'Summon Demon', no:'Kalle frem demon', ctx:'Summon pet demon' },
        { en:'Dark Pact', no:'Mørk pakt', ctx:'Convert pet mana to caster mana' },
        { en:'Life Tap', no:'Livstapping', ctx:'Convert HP to mana' },
      ],
      playstyle:[
        { en:'Affliction', no:'Lidelse', ctx:'DoT spec — sustained damage' },
        { en:'Demonology', no:'Demonologi', ctx:'Pet spec — tank pet' },
        { en:'Destruction', no:'Ødeleggelse', ctx:'Direct damage nuke spec' },
        { en:'Soulstone rotation', no:'Sjelsteinrotasjon', ctx:'Battle rez utility' },
        { en:'Curse management', no:'Forbannelseshåndtering', ctx:'Only one curse per target' },
        { en:'Dot management', no:'Punktskadehåndtering', ctx:'Keep all DoTs up' },
        { en:'Pet management', no:'Kjæledyrstyring', ctx:'Control demon pet' },
      ],
      advanced:[
        { en:'Haunt', no:'Hjemsøke', ctx:'TBC Affliction signature' },
        { en:'Unstable Affliction', no:'Ustabil lidelse', ctx:'TBC — dispel punishment' },
        { en:'Metamorphosis', no:'Metamorfose', ctx:'TBC Demo — transform demon form' },
        { en:'Conflagrate', no:'Antenne', ctx:'Consume Immolate for burst' },
        { en:'Chaos Bolt', no:'Kaosbolt', ctx:'TBC Destro — ignore resist' },
      ],
    }},

    rogue: { icon:'🗡', faction:'both', label:'Rogue', cards:{
      weapons:[
        { en:'Dagger', no:'Dolk', ctx:'Rogue main weapon (combat backstab)' },
        { en:'Sword (one-handed)', no:'Etterhåndssverd', ctx:'Combat rogue weapon' },
        { en:'Fist weapon', no:'Nevevåpen', ctx:'Rogue weapon option' },
        { en:'Mace (one-handed)', no:'Etterhåndskølle', ctx:'Rogue weapon' },
        { en:'Thrown weapon', no:'Kastevåpen', ctx:'Rogue ranged pull' },
        { en:'Bow', no:'Bue', ctx:'Rogue ranged option' },
      ],
      armor:[
        { en:'Leather armor', no:'Lærpanser', ctx:'Rogue only armor' },
        { en:'Cloth armor', no:'Tøypanser', ctx:'Very early rogue gear' },
      ],
      abilities:[
        { en:'Stealth', no:'Skjult', ctx:'Core rogue ability — invisible' },
        { en:'Backstab', no:'Ryggangrep', ctx:'Must be behind — huge hit' },
        { en:'Sinister Strike', no:'Uheilsvarslet slag', ctx:'Main combo builder' },
        { en:'Eviscerate', no:'Utnulling', ctx:'Combo point finisher — damage' },
        { en:'Slice and Dice', no:'Skjær og finhakk', ctx:'Combo finisher — attack speed' },
        { en:'Rupture', no:'Sprekke', ctx:'Combo finisher — bleed DoT' },
        { en:'Kidney Shot', no:'Nyreskudd', ctx:'Combo finisher — stun' },
        { en:'Ambush', no:'Bakhold', ctx:'Stealth opener — huge crit' },
        { en:'Garrote', no:'Kvelning', ctx:'Stealth opener — silence DoT' },
        { en:'Cheap Shot', no:'Lavt slag', ctx:'Stealth opener — stun' },
        { en:'Sap', no:'Batong', ctx:'Stealth CC — Humanoids' },
        { en:'Vanish', no:'Forsvinne', ctx:'Drop combat, re-stealth' },
        { en:'Kick', no:'Spark', ctx:'Interrupt' },
        { en:'Evasion', no:'Unnviking', ctx:'Dodge chance cooldown' },
        { en:'Sprint', no:'Sprint', ctx:'Movement speed burst' },
        { en:'Blind', no:'Blinde', ctx:'CC — disorient' },
      ],
      playstyle:[
        { en:'Combat', no:'Kamp', ctx:'Sustained cleave DPS spec' },
        { en:'Subtlety', no:'Finesse', ctx:'PvP stealth spec' },
        { en:'Assassination', no:'Attentat', ctx:'Dagger/poison spec' },
        { en:'Energy resource', no:'Energiressurs', ctx:'Rogue uses Energy (not mana)' },
        { en:'Combo points', no:'Kombopoeng', ctx:'1-5 stacks before finisher' },
        { en:'Poison application', no:'Giftpåføring', ctx:'Apply to weapon before fight' },
        { en:'Position awareness', no:'Posisjonsbevissthet', ctx:'Must be behind for backstab' },
      ],
      advanced:[
        { en:'Preparation', no:'Forberedelse', ctx:'Reset all cooldowns' },
        { en:'Cold Blood', no:'Kaldt blod', ctx:'Guaranteed crit next ability' },
        { en:'Adrenaline Rush', no:'Adrenalinkick', ctx:'Energy regen doubled' },
        { en:'Blade Flurry', no:'Klinge-byge', ctx:'AoE attack speed buff' },
        { en:'Expose Armor', no:'Avsløre rustning', ctx:'Combo finisher — armor debuff' },
      ],
    }},

  },

};

// ═══════════════════════════════════════════════════════
//  AUDIO ENGINE  (Web Audio API — no files needed)
// ═══════════════════════════════════════════════════════
